import { useNavigate } from 'react-router-dom';
import { useCampaigns } from '../hooks/useCampaigns';
import { useBalance } from '../hooks/useBalance';
import { useContentPieces } from '../hooks/useContentPieces';
import { CampaignCard } from '../components/CampaignCard';

export const Home = () => {
  const navigate = useNavigate();
  const { campaigns, loading: campaignsLoading } = useCampaigns();
  const { content } = useContentPieces();
  const { balance } = useBalance();

  const completedCampaigns = campaigns.filter((c) => c.status === 'completed');
  const totalContent = content.length;
  const totalSpent = campaigns.reduce((sum, c) => sum + parseFloat(c.totalCost || '0'), 0);
  const recentCampaigns = campaigns.slice(0, 3);

  return (
    <div className="max-w-4xl mx-auto px-4 py-6 flex flex-col gap-8">
      {/* Hero */}
      <div className="text-center flex flex-col items-center gap-4 pt-4">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-primary/10 border border-primary/20 rounded-full text-xs text-primary font-medium">
          <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
          5 AI agents · x402 payments · Powered by FND
        </div>

        <h1 className="text-2xl sm:text-3xl font-bold text-foreground max-w-md">
          Agentic Content Swarm for Frontier Tower
        </h1>

        <p className="text-sm text-muted-foreground max-w-sm">
          Brief the swarm. Pay once in FND. Get platform-native content for Twitter, LinkedIn, Instagram, and Farcaster — generated by 5 coordinated AI agents.
        </p>

        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/campaigns/new')}
            className="px-5 py-2.5 bg-primary text-white text-sm font-semibold rounded-xl hover:bg-primary/90 transition-colors"
          >
            Launch Swarm
          </button>
          <button
            onClick={() => navigate('/campaigns')}
            className="px-5 py-2.5 border border-border text-sm font-medium text-foreground rounded-xl hover:bg-muted-background transition-colors"
          >
            View Campaigns
          </button>
        </div>

        {/* Balance pill */}
        {balance && (
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <div className="w-2 h-2 rounded-full bg-success" />
            Wallet: <span className="text-foreground font-medium">{balance.total} FND</span>
          </div>
        )}
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Campaigns Run', value: completedCampaigns.length.toString() },
          { label: 'Content Pieces', value: totalContent.toString() },
          { label: 'FND Spent', value: totalSpent.toFixed(2) },
        ].map((stat) => (
          <div key={stat.label} className="bg-card border border-border rounded-xl p-3 text-center">
            <p className="text-base font-bold text-foreground">{stat.value}</p>
            <p className="text-xs text-muted-foreground mt-0.5">{stat.label}</p>
          </div>
        ))}
      </div>

      {/* Recent Campaigns */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-foreground">Recent Campaigns</h2>
          <button
            onClick={() => navigate('/campaigns')}
            className="text-xs text-primary hover:underline"
          >
            View all →
          </button>
        </div>

        {campaignsLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {[1, 2, 3].map((i) => (
              <div key={i} className="bg-card border border-border rounded-xl p-4 h-32 animate-pulse" />
            ))}
          </div>
        ) : recentCampaigns.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {recentCampaigns.map((campaign) => (
              <CampaignCard
                key={campaign.id}
                campaign={campaign}
                onClick={() => navigate(`/campaigns/${campaign.id}`)}
              />
            ))}
          </div>
        ) : (
          <div className="bg-card border border-border rounded-xl p-8 text-center">
            <p className="text-xs text-muted-foreground">No campaigns yet. Launch your first swarm!</p>
          </div>
        )}
      </div>

      {/* How it works */}
      <div className="bg-primary/5 border border-primary/15 rounded-xl p-4 flex flex-col gap-3">
        <h3 className="text-sm font-semibold text-foreground">How the Swarm Works</h3>
        <ol className="flex flex-col gap-1.5">
          {[
            'Define your campaign — title, brief, target audience, platforms, and tone',
            'Pay 0.23 FND to activate the swarm (covers all 5 agent runs via x402)',
            'StrategyBot plans the content strategy for each platform',
            'CopyForge writes platform-native copy, ToneShift adapts it',
            'VisualCraft creates image prompts, HashSwarm picks the best hashtags',
            'Review generated content, schedule it, and copy to your social accounts',
          ].map((step, i) => (
            <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
              <span className="w-4 h-4 rounded-full bg-primary/20 text-primary text-xs flex items-center justify-center flex-shrink-0 mt-0.5 font-semibold">
                {i + 1}
              </span>
              {step}
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
};
